services:
  mysql_db:
    platform: linux/x86_64
    image: mysql:5.7
    container_name: mysql
    environment:
      - MYSQL_DATABASE=tour_of_heroes_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
  app:
    depends_on:
      - mysql_db
    image: pavlogook/tour-of-heroes-backend
    build:
      context: .
    env_file: ./.env
    container_name: tour-of-heroes-app
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
      - $DEBUG_PORT:$DEBUG_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url" : "jdbc:mysql://mysql_db:3306/tour_of_heroes_db",
        "spring.datasource.username" : "user",
        "spring.datasource.password" : "password",
        "spring.jpa.hibernate.ddl-auto" : "validate"
        }'
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
